### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by jonyeezs** [atom/language-puppet#11]
[Enter steps to reproduce below:]

1. In Settings > Instasll Package
2. search markdown . Result on preview-plus.
4. Click instasll on that package.

**Atom Version**: 0.187.0
**System**: Microsoft Windows 8 Enterprise
**Thrown From**: [language-puppet](https://github.com/atom/language-puppet) package, v0.10.0

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:201

TypeError: Arguments to path.join must be strings
  at f (path.js:201:13)
  at Object.filter (native)
  at Object.win32.join (path.js:206:38)
  at PackageGrammarsView.module.exports.PackageGrammarsView.initialize (C:\Users\JonathanY\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-grammars-view.js:37:31)
  at PackageGrammarsView.View (C:\Users\JonathanY\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new PackageGrammarsView (C:\Users\JonathanY\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-grammars-view.js:20:56)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (C:\Users\JonathanY\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-detail-view.js:189:30)
  at PackageDetailView.module.exports.PackageDetailView.populate (C:\Users\JonathanY\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-detail-view.js:177:19)
  at PackageDetailView.module.exports.PackageDetailView.initialize (C:\Users\JonathanY\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-detail-view.js:143:12)
  at PackageDetailView.View (C:\Users\JonathanY\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new PackageDetailView (C:\Users\JonathanY\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-detail-view.js:38:54)
  at C:\Users\JonathanY\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\settings-view.js:282:22
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (C:\Users\JonathanY\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\settings-view.js:287:19)
  at SettingsView.module.exports.SettingsView.showPanel (C:\Users\JonathanY\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\settings-view.js:323:24)
  at space-pen-div.<anonymous> (C:\Users\JonathanY\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-card.js:171:26)
  at space-pen-div.jQuery.event.dispatch (C:\Users\JonathanY\AppData\Local\atom\app-0.187.0\resources\app\node_modules\jquery\dist\jquery.js:4430:9)
  at space-pen-div.elemData.handle (C:\Users\JonathanY\AppData\Local\atom\app-0.187.0\resources\app\node_modules\jquery\dist\jquery.js:4116:28)

```

### Commands

```
     -2:17.3 editor:newline (atom-text-editor.editor)
  5x -2:15.5 core:backspace (atom-text-editor.editor)
     -2:12.8 core:move-up (atom-text-editor.editor)
     -2:12.5 editor:newline (atom-text-editor.editor)
     -2:10.0 core:move-down (atom-text-editor.editor)
     -2:09.6 editor:newline (atom-text-editor.editor)
     -2:05.6 core:save (atom-text-editor.editor)
     -1:55.4 markdown-preview:toggle (atom-text-editor.editor)
     -1:41.6 core:save (atom-text-editor.editor)
     -1:35.4 core:move-right (atom-text-editor.editor)
     -1:35.0 core:move-left (atom-text-editor.editor)
  4x -1:34.5 core:select-left (atom-text-editor.editor)
 16x -1:32.5 core:move-right (atom-text-editor.editor)
  5x -1:30.8 core:select-right (atom-text-editor.editor)
     -1:29.7 core:select-left (atom-text-editor.editor)
     -1:27.8 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-puppet, v0.10.0
preview-plus, v1.1.19

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
This is a bug in the settings view that will be fixed via https://github.com/atom/settings-view/issues/417 please subscribe there for updates.
